"""New tables Product and Category Table

Revision ID: 914219127156
Revises: d0efad957c13
Create Date: 2024-11-07 21:44:27.378923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '914219127156'
down_revision: Union[str, None] = 'd0efad957c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
    sa.Column('image_public_id', sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
    sa.Column('image_version', sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('old_price', sa.Float(), nullable=True),
    sa.Column('product_location', sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
    sa.Column('availability', sa.Integer(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('visits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('category')
    # ### end Alembic commands ###
