"""New Table Order created

Revision ID: a96094ced374
Revises: ab317e5742d1
Create Date: 2024-11-13 09:54:39.490564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a96094ced374'
down_revision: Union[str, None] = 'ab317e5742d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('order_code', sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('main_order_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['color.id'], ),
    sa.ForeignKeyConstraint(['main_order_id'], ['mainorder.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
