"""New Table special packages

Revision ID: ab317e5742d1
Revises: 03c04d532e99
Create Date: 2024-11-13 09:47:44.939920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ab317e5742d1'
down_revision: Union[str, None] = '03c04d532e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialpackage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_name', sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
    sa.Column('discount_price', sa.Float(), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=False),
    sa.Column('availability', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specialpackage')
    # ### end Alembic commands ###
