"""Colmn name changed from str to bool

Revision ID: ad8c4cf7bec7
Revises: 4274e372c9c5
Create Date: 2024-11-07 14:18:00.066437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ad8c4cf7bec7'
down_revision: Union[str, None] = '4274e372c9c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'activation',
               existing_type=mysql.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('user', 'role',
               existing_type=mysql.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('user', 'activation',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
