"""Column bool to int [role]

Revision ID: ccb35a6451e5
Revises: ad8c4cf7bec7
Create Date: 2024-11-07 14:23:43.175453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ccb35a6451e5'
down_revision: Union[str, None] = 'ad8c4cf7bec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
