"""Colmn Data Type Chanegd

Revision ID: d0efad957c13
Revises: ff46b5b72c14
Create Date: 2024-11-07 14:54:00.425752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd0efad957c13'
down_revision: Union[str, None] = 'ff46b5b72c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'activation',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('user', 'email_verified_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('user', 'photo_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'image_version',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'shop_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'phone_number',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'phone_number2',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'phone_number3',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'about_shop',
               existing_type=mysql.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=True)
    op.alter_column('user', 'credit',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('user', 'tin',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'business_type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'remember_token',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('user', 'updated_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
    op.alter_column('user', 'remember_token',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'business_type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'tin',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'credit',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('user', 'about_shop',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.INTEGER(),
               nullable=False)
    op.alter_column('user', 'phone_number3',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'phone_number2',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'phone_number',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'shop_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'image_version',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'photo_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'email_verified_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
    op.alter_column('user', 'activation',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    # ### end Alembic commands ###
